logfile = "" # log file location
loglevel = "DEBUG" # CRITICAL|ERROR|WARNING|NOTICE|INFO|DEBUG
instancename = "proxy" # instance name
certpem = "C:/daten/go/certs/info_age_proxy.pem" # tls server certificate file in PEM format
keypem = "C:/daten/go/certs/info_age_proxy.key" # tls server key file in PEM format
capem = "C:/daten/go/certs/info_age_ca.pem" # tls root certificate file in PEM format
tlsaddr = "localhost:7777" # listen address for incoming raw tls connections
webroot = "C:/daten/go/src/github.com/je4/bremote/proxy/htdocs"
kvdbfile = "C:/daten/go/src/github.com/je4/bremote/proxy/kv.bitcask"
ntphost = "localhost"
