logfile = "" # log file location
loglevel = "DEBUG" # CRITICAL|ERROR|WARNING|NOTICE|INFO|DEBUG
instancename = "proxy" # instance name
certpem = "certs/info_age_mediathek_proxy.pem" # tls client certificate file in PEM format
keypem = "certs/info_age_mediathek_proxy.key" # tls client key file in PEM format
capem = "certs/info_age_mediathek_ca.pem" # tls root certificate file in PEM format
httpscertpem = "certs/info_age_localhost.pem" # tls client certificate file in PEM format
httpskeypem = "certs/info_age_localhost.key" # tls client key file in PEM format
tlsaddr = "localhost:7777" # listen address for incoming raw tls connections
webroot = "C:/daten/go/dev/bremote/proxy/htdocs"
kvdbfile = "C:/daten/go/dev/bremote/proxy/kv.bitcask"
ntphost = "localhost"
runtimeinterval = "0m10s"

