// Code generated by protoc-gen-go. DO NOT EDIT.
// source: client.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type BrowserInitFlag struct {
	Name string `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	// Types that are valid to be assigned to Value:
	//	*BrowserInitFlag_Strval
	//	*BrowserInitFlag_Bval
	Value                isBrowserInitFlag_Value `protobuf_oneof:"value"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *BrowserInitFlag) Reset()         { *m = BrowserInitFlag{} }
func (m *BrowserInitFlag) String() string { return proto.CompactTextString(m) }
func (*BrowserInitFlag) ProtoMessage()    {}
func (*BrowserInitFlag) Descriptor() ([]byte, []int) {
	return fileDescriptor_014de31d7ac8c57c, []int{0}
}

func (m *BrowserInitFlag) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BrowserInitFlag.Unmarshal(m, b)
}
func (m *BrowserInitFlag) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BrowserInitFlag.Marshal(b, m, deterministic)
}
func (m *BrowserInitFlag) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BrowserInitFlag.Merge(m, src)
}
func (m *BrowserInitFlag) XXX_Size() int {
	return xxx_messageInfo_BrowserInitFlag.Size(m)
}
func (m *BrowserInitFlag) XXX_DiscardUnknown() {
	xxx_messageInfo_BrowserInitFlag.DiscardUnknown(m)
}

var xxx_messageInfo_BrowserInitFlag proto.InternalMessageInfo

func (m *BrowserInitFlag) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type isBrowserInitFlag_Value interface {
	isBrowserInitFlag_Value()
}

type BrowserInitFlag_Strval struct {
	Strval string `protobuf:"bytes,2,opt,name=strval,proto3,oneof"`
}

type BrowserInitFlag_Bval struct {
	Bval bool `protobuf:"varint,3,opt,name=bval,proto3,oneof"`
}

func (*BrowserInitFlag_Strval) isBrowserInitFlag_Value() {}

func (*BrowserInitFlag_Bval) isBrowserInitFlag_Value() {}

func (m *BrowserInitFlag) GetValue() isBrowserInitFlag_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *BrowserInitFlag) GetStrval() string {
	if x, ok := m.GetValue().(*BrowserInitFlag_Strval); ok {
		return x.Strval
	}
	return ""
}

func (m *BrowserInitFlag) GetBval() bool {
	if x, ok := m.GetValue().(*BrowserInitFlag_Bval); ok {
		return x.Bval
	}
	return false
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*BrowserInitFlag) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*BrowserInitFlag_Strval)(nil),
		(*BrowserInitFlag_Bval)(nil),
	}
}

type NavigateParam struct {
	Url                  string   `protobuf:"bytes,1,opt,name=Url,proto3" json:"Url,omitempty"`
	NextStatus           string   `protobuf:"bytes,2,opt,name=NextStatus,proto3" json:"NextStatus,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NavigateParam) Reset()         { *m = NavigateParam{} }
func (m *NavigateParam) String() string { return proto.CompactTextString(m) }
func (*NavigateParam) ProtoMessage()    {}
func (*NavigateParam) Descriptor() ([]byte, []int) {
	return fileDescriptor_014de31d7ac8c57c, []int{1}
}

func (m *NavigateParam) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NavigateParam.Unmarshal(m, b)
}
func (m *NavigateParam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NavigateParam.Marshal(b, m, deterministic)
}
func (m *NavigateParam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NavigateParam.Merge(m, src)
}
func (m *NavigateParam) XXX_Size() int {
	return xxx_messageInfo_NavigateParam.Size(m)
}
func (m *NavigateParam) XXX_DiscardUnknown() {
	xxx_messageInfo_NavigateParam.DiscardUnknown(m)
}

var xxx_messageInfo_NavigateParam proto.InternalMessageInfo

func (m *NavigateParam) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *NavigateParam) GetNextStatus() string {
	if m != nil {
		return m.NextStatus
	}
	return ""
}

type BrowserInitFlags struct {
	Flags                []*BrowserInitFlag `protobuf:"bytes,1,rep,name=flags,proto3" json:"flags,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *BrowserInitFlags) Reset()         { *m = BrowserInitFlags{} }
func (m *BrowserInitFlags) String() string { return proto.CompactTextString(m) }
func (*BrowserInitFlags) ProtoMessage()    {}
func (*BrowserInitFlags) Descriptor() ([]byte, []int) {
	return fileDescriptor_014de31d7ac8c57c, []int{2}
}

func (m *BrowserInitFlags) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BrowserInitFlags.Unmarshal(m, b)
}
func (m *BrowserInitFlags) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BrowserInitFlags.Marshal(b, m, deterministic)
}
func (m *BrowserInitFlags) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BrowserInitFlags.Merge(m, src)
}
func (m *BrowserInitFlags) XXX_Size() int {
	return xxx_messageInfo_BrowserInitFlags.Size(m)
}
func (m *BrowserInitFlags) XXX_DiscardUnknown() {
	xxx_messageInfo_BrowserInitFlags.DiscardUnknown(m)
}

var xxx_messageInfo_BrowserInitFlags proto.InternalMessageInfo

func (m *BrowserInitFlags) GetFlags() []*BrowserInitFlag {
	if m != nil {
		return m.Flags
	}
	return nil
}

func init() {
	proto.RegisterType((*BrowserInitFlag)(nil), "info_age.bremote.BrowserInitFlag")
	proto.RegisterType((*NavigateParam)(nil), "info_age.bremote.NavigateParam")
	proto.RegisterType((*BrowserInitFlags)(nil), "info_age.bremote.BrowserInitFlags")
}

func init() { proto.RegisterFile("client.proto", fileDescriptor_014de31d7ac8c57c) }

var fileDescriptor_014de31d7ac8c57c = []byte{
	// 406 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x53, 0x5d, 0x6b, 0xd4, 0x40,
	0x14, 0xdd, 0x35, 0xdb, 0xda, 0xbd, 0x6d, 0xe9, 0x32, 0x14, 0x89, 0x5b, 0xd0, 0x35, 0x4f, 0xfb,
	0x62, 0x0a, 0xf5, 0xc1, 0x17, 0xa1, 0x34, 0xa5, 0x5a, 0x51, 0x97, 0x92, 0x20, 0x82, 0x0f, 0xca,
	0x64, 0xbd, 0x3b, 0x0e, 0x26, 0x33, 0x61, 0xe6, 0x26, 0xb5, 0x3f, 0xda, 0xff, 0x20, 0xf9, 0x92,
	0x9a, 0x25, 0xe9, 0xdb, 0xfd, 0x3c, 0xf7, 0xcc, 0x39, 0x0c, 0x1c, 0xac, 0x13, 0x89, 0x8a, 0xfc,
	0xcc, 0x68, 0xd2, 0x6c, 0x26, 0xd5, 0x46, 0x7f, 0xe7, 0x02, 0xfd, 0xd8, 0x60, 0xaa, 0x09, 0xe7,
	0x27, 0x42, 0x6b, 0x91, 0xe0, 0x69, 0xd5, 0x8f, 0xf3, 0xcd, 0x29, 0xa6, 0x19, 0xdd, 0xd5, 0xe3,
	0xf3, 0xa7, 0xdd, 0x26, 0x57, 0x6d, 0x6b, 0x9f, 0xee, 0x32, 0xb4, 0x75, 0xe2, 0x7d, 0x83, 0xa3,
	0xc0, 0xe8, 0x5b, 0x8b, 0xe6, 0xbd, 0x92, 0xf4, 0x36, 0xe1, 0x82, 0x31, 0x98, 0xac, 0x78, 0x8a,
	0xee, 0x78, 0x31, 0x5e, 0x4e, 0xc3, 0x2a, 0x66, 0x2e, 0xec, 0x5a, 0x32, 0x05, 0x4f, 0xdc, 0x47,
	0x65, 0xf5, 0x7a, 0x14, 0x36, 0x39, 0x3b, 0x86, 0x49, 0x5c, 0xd6, 0x9d, 0xc5, 0x78, 0xb9, 0x77,
	0x3d, 0x0a, 0xab, 0x2c, 0x78, 0x0c, 0x3b, 0x05, 0x4f, 0x72, 0xf4, 0x2e, 0xe0, 0x70, 0xc5, 0x0b,
	0x29, 0x38, 0xe1, 0x0d, 0x37, 0x3c, 0x65, 0x33, 0x70, 0x3e, 0x9b, 0xa4, 0x01, 0x2f, 0x43, 0xf6,
	0x0c, 0x60, 0x85, 0xbf, 0x29, 0x22, 0x4e, 0xb9, 0xad, 0xf1, 0xc3, 0x7b, 0x15, 0xef, 0x03, 0xcc,
	0x3a, 0x14, 0x2d, 0x7b, 0x0d, 0x3b, 0x9b, 0x32, 0x70, 0xc7, 0x0b, 0x67, 0xb9, 0x7f, 0xf6, 0xc2,
	0xef, 0xaa, 0xe3, 0x77, 0x56, 0xc2, 0x7a, 0xfe, 0xec, 0x8f, 0x03, 0x87, 0x97, 0x95, 0xae, 0x11,
	0x9a, 0x42, 0xae, 0x91, 0xbd, 0x81, 0xc9, 0x8d, 0x54, 0x82, 0xb9, 0xdb, 0x18, 0x11, 0x19, 0xa9,
	0xc4, 0xbc, 0xb7, 0xe3, 0x8d, 0xd8, 0x47, 0x38, 0x88, 0x88, 0x1b, 0x6a, 0xce, 0x31, 0xef, 0x41,
	0x26, 0x76, 0xfe, 0xc4, 0xaf, 0xcd, 0xf1, 0x5b, 0x73, 0xfc, 0xab, 0xd2, 0x39, 0x6f, 0xc4, 0xae,
	0x60, 0xaf, 0x55, 0x8b, 0x3d, 0xdf, 0x46, 0xfa, 0x4f, 0xc9, 0x01, 0x98, 0x4b, 0x38, 0x8a, 0x7e,
	0xe6, 0xf4, 0x43, 0xdf, 0xaa, 0x96, 0x57, 0xcf, 0xf0, 0x00, 0xc8, 0x39, 0x4c, 0xdf, 0x61, 0xe3,
	0x41, 0xef, 0xfa, 0x90, 0x34, 0xe7, 0x30, 0x8d, 0xfe, 0x01, 0xf4, 0xab, 0xdb, 0xcf, 0x20, 0x80,
	0xd9, 0x17, 0x8c, 0x23, 0xbd, 0xfe, 0x85, 0xf4, 0x09, 0xad, 0xe5, 0x02, 0xd9, 0xf1, 0xd6, 0xf4,
	0x85, 0x1a, 0x78, 0x45, 0xe0, 0xc1, 0x89, 0x42, 0xaa, 0x8e, 0xbf, 0xbc, 0x7f, 0xbc, 0xfe, 0x5b,
	0x5f, 0x1d, 0x9e, 0xc9, 0x78, 0xb7, 0xda, 0x7a, 0xf5, 0x37, 0x00, 0x00, 0xff, 0xff, 0x4b, 0x74,
	0x20, 0xfd, 0x71, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ClientServiceClient is the client API for ClientService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ClientServiceClient interface {
	Ping(ctx context.Context, in *String, opts ...grpc.CallOption) (*String, error)
	StartBrowser(ctx context.Context, in *BrowserInitFlags, opts ...grpc.CallOption) (*empty.Empty, error)
	Navigate(ctx context.Context, in *NavigateParam, opts ...grpc.CallOption) (*empty.Empty, error)
	ShutdownBrowser(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*empty.Empty, error)
	GetStatus(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*String, error)
	SetStatus(ctx context.Context, in *String, opts ...grpc.CallOption) (*empty.Empty, error)
	WebSocketMessage(ctx context.Context, in *any.Any, opts ...grpc.CallOption) (*empty.Empty, error)
}

type clientServiceClient struct {
	cc *grpc.ClientConn
}

func NewClientServiceClient(cc *grpc.ClientConn) ClientServiceClient {
	return &clientServiceClient{cc}
}

func (c *clientServiceClient) Ping(ctx context.Context, in *String, opts ...grpc.CallOption) (*String, error) {
	out := new(String)
	err := c.cc.Invoke(ctx, "/info_age.bremote.ClientService/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientServiceClient) StartBrowser(ctx context.Context, in *BrowserInitFlags, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/info_age.bremote.ClientService/StartBrowser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientServiceClient) Navigate(ctx context.Context, in *NavigateParam, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/info_age.bremote.ClientService/Navigate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientServiceClient) ShutdownBrowser(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/info_age.bremote.ClientService/ShutdownBrowser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientServiceClient) GetStatus(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*String, error) {
	out := new(String)
	err := c.cc.Invoke(ctx, "/info_age.bremote.ClientService/GetStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientServiceClient) SetStatus(ctx context.Context, in *String, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/info_age.bremote.ClientService/SetStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientServiceClient) WebSocketMessage(ctx context.Context, in *any.Any, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/info_age.bremote.ClientService/WebSocketMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClientServiceServer is the server API for ClientService service.
type ClientServiceServer interface {
	Ping(context.Context, *String) (*String, error)
	StartBrowser(context.Context, *BrowserInitFlags) (*empty.Empty, error)
	Navigate(context.Context, *NavigateParam) (*empty.Empty, error)
	ShutdownBrowser(context.Context, *empty.Empty) (*empty.Empty, error)
	GetStatus(context.Context, *empty.Empty) (*String, error)
	SetStatus(context.Context, *String) (*empty.Empty, error)
	WebSocketMessage(context.Context, *any.Any) (*empty.Empty, error)
}

// UnimplementedClientServiceServer can be embedded to have forward compatible implementations.
type UnimplementedClientServiceServer struct {
}

func (*UnimplementedClientServiceServer) Ping(ctx context.Context, req *String) (*String, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (*UnimplementedClientServiceServer) StartBrowser(ctx context.Context, req *BrowserInitFlags) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartBrowser not implemented")
}
func (*UnimplementedClientServiceServer) Navigate(ctx context.Context, req *NavigateParam) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Navigate not implemented")
}
func (*UnimplementedClientServiceServer) ShutdownBrowser(ctx context.Context, req *empty.Empty) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ShutdownBrowser not implemented")
}
func (*UnimplementedClientServiceServer) GetStatus(ctx context.Context, req *empty.Empty) (*String, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStatus not implemented")
}
func (*UnimplementedClientServiceServer) SetStatus(ctx context.Context, req *String) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetStatus not implemented")
}
func (*UnimplementedClientServiceServer) WebSocketMessage(ctx context.Context, req *any.Any) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WebSocketMessage not implemented")
}

func RegisterClientServiceServer(s *grpc.Server, srv ClientServiceServer) {
	s.RegisterService(&_ClientService_serviceDesc, srv)
}

func _ClientService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(String)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/info_age.bremote.ClientService/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientServiceServer).Ping(ctx, req.(*String))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientService_StartBrowser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BrowserInitFlags)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientServiceServer).StartBrowser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/info_age.bremote.ClientService/StartBrowser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientServiceServer).StartBrowser(ctx, req.(*BrowserInitFlags))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientService_Navigate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NavigateParam)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientServiceServer).Navigate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/info_age.bremote.ClientService/Navigate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientServiceServer).Navigate(ctx, req.(*NavigateParam))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientService_ShutdownBrowser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientServiceServer).ShutdownBrowser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/info_age.bremote.ClientService/ShutdownBrowser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientServiceServer).ShutdownBrowser(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientService_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientServiceServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/info_age.bremote.ClientService/GetStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientServiceServer).GetStatus(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientService_SetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(String)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientServiceServer).SetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/info_age.bremote.ClientService/SetStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientServiceServer).SetStatus(ctx, req.(*String))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientService_WebSocketMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(any.Any)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientServiceServer).WebSocketMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/info_age.bremote.ClientService/WebSocketMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientServiceServer).WebSocketMessage(ctx, req.(*any.Any))
	}
	return interceptor(ctx, in, info, handler)
}

var _ClientService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "info_age.bremote.ClientService",
	HandlerType: (*ClientServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _ClientService_Ping_Handler,
		},
		{
			MethodName: "StartBrowser",
			Handler:    _ClientService_StartBrowser_Handler,
		},
		{
			MethodName: "Navigate",
			Handler:    _ClientService_Navigate_Handler,
		},
		{
			MethodName: "ShutdownBrowser",
			Handler:    _ClientService_ShutdownBrowser_Handler,
		},
		{
			MethodName: "GetStatus",
			Handler:    _ClientService_GetStatus_Handler,
		},
		{
			MethodName: "SetStatus",
			Handler:    _ClientService_SetStatus_Handler,
		},
		{
			MethodName: "WebSocketMessage",
			Handler:    _ClientService_WebSocketMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "client.proto",
}
