// Code generated by protoc-gen-go. DO NOT EDIT.
// source: controller.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type NewClientParam struct {
	Client               string           `protobuf:"bytes,1,opt,name=client,proto3" json:"client,omitempty"`
	Status               string           `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	HttpAddr             string           `protobuf:"bytes,3,opt,name=httpAddr,proto3" json:"httpAddr,omitempty"`
	Type                 ProxySessionType `protobuf:"varint,4,opt,name=type,proto3,enum=info_age.bremote.ProxySessionType" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *NewClientParam) Reset()         { *m = NewClientParam{} }
func (m *NewClientParam) String() string { return proto.CompactTextString(m) }
func (*NewClientParam) ProtoMessage()    {}
func (*NewClientParam) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed7f10298fa1d90f, []int{0}
}

func (m *NewClientParam) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewClientParam.Unmarshal(m, b)
}
func (m *NewClientParam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewClientParam.Marshal(b, m, deterministic)
}
func (m *NewClientParam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewClientParam.Merge(m, src)
}
func (m *NewClientParam) XXX_Size() int {
	return xxx_messageInfo_NewClientParam.Size(m)
}
func (m *NewClientParam) XXX_DiscardUnknown() {
	xxx_messageInfo_NewClientParam.DiscardUnknown(m)
}

var xxx_messageInfo_NewClientParam proto.InternalMessageInfo

func (m *NewClientParam) GetClient() string {
	if m != nil {
		return m.Client
	}
	return ""
}

func (m *NewClientParam) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *NewClientParam) GetHttpAddr() string {
	if m != nil {
		return m.HttpAddr
	}
	return ""
}

func (m *NewClientParam) GetType() ProxySessionType {
	if m != nil {
		return m.Type
	}
	return ProxySessionType_Undefined
}

type TemplateList struct {
	Template             []string `protobuf:"bytes,1,rep,name=template,proto3" json:"template,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TemplateList) Reset()         { *m = TemplateList{} }
func (m *TemplateList) String() string { return proto.CompactTextString(m) }
func (*TemplateList) ProtoMessage()    {}
func (*TemplateList) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed7f10298fa1d90f, []int{1}
}

func (m *TemplateList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TemplateList.Unmarshal(m, b)
}
func (m *TemplateList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TemplateList.Marshal(b, m, deterministic)
}
func (m *TemplateList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TemplateList.Merge(m, src)
}
func (m *TemplateList) XXX_Size() int {
	return xxx_messageInfo_TemplateList.Size(m)
}
func (m *TemplateList) XXX_DiscardUnknown() {
	xxx_messageInfo_TemplateList.DiscardUnknown(m)
}

var xxx_messageInfo_TemplateList proto.InternalMessageInfo

func (m *TemplateList) GetTemplate() []string {
	if m != nil {
		return m.Template
	}
	return nil
}

func init() {
	proto.RegisterType((*NewClientParam)(nil), "info_age.bremote.NewClientParam")
	proto.RegisterType((*TemplateList)(nil), "info_age.bremote.TemplateList")
}

func init() { proto.RegisterFile("controller.proto", fileDescriptor_ed7f10298fa1d90f) }

var fileDescriptor_ed7f10298fa1d90f = []byte{
	// 362 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x92, 0x41, 0x6b, 0xea, 0x40,
	0x14, 0x85, 0x8d, 0x8a, 0x3c, 0xe7, 0x89, 0xf8, 0x66, 0xe1, 0x0b, 0x29, 0xb4, 0x21, 0x8b, 0x22,
	0x85, 0x46, 0xb0, 0xd0, 0x55, 0x37, 0x55, 0xc4, 0x2e, 0xda, 0x22, 0x2a, 0x14, 0xba, 0x29, 0x49,
	0xbc, 0xa6, 0x43, 0x93, 0x99, 0x61, 0xe6, 0x6a, 0x9b, 0xff, 0xd1, 0xff, 0xd9, 0xbf, 0x50, 0x92,
	0xa8, 0xb5, 0x0d, 0xe9, 0xf2, 0xdc, 0x7b, 0x38, 0xe7, 0xf2, 0xcd, 0x90, 0x4e, 0x20, 0x38, 0x2a,
	0x11, 0x45, 0xa0, 0x5c, 0xa9, 0x04, 0x0a, 0xda, 0x61, 0x7c, 0x25, 0x9e, 0xbc, 0x10, 0x5c, 0x5f,
	0x41, 0x2c, 0x10, 0xac, 0xa3, 0x50, 0x88, 0x30, 0x82, 0x7e, 0xb6, 0xf7, 0xd7, 0xab, 0x3e, 0xc4,
	0x12, 0x93, 0xdc, 0x6e, 0xfd, 0xc5, 0x44, 0x82, 0xce, 0x85, 0xf3, 0x6e, 0x90, 0xf6, 0x3d, 0xbc,
	0x8e, 0x22, 0x06, 0x1c, 0xa7, 0x9e, 0xf2, 0x62, 0xda, 0x25, 0x8d, 0x20, 0x93, 0xa6, 0x61, 0x1b,
	0xbd, 0xe6, 0x6c, 0xab, 0xd2, 0xb9, 0x46, 0x0f, 0xd7, 0xda, 0xac, 0xe6, 0xf3, 0x5c, 0x51, 0x8b,
	0xfc, 0x79, 0x46, 0x94, 0xd7, 0xcb, 0xa5, 0x32, 0x6b, 0xd9, 0x66, 0xaf, 0xe9, 0x25, 0xa9, 0xa7,
	0x6d, 0x66, 0xdd, 0x36, 0x7a, 0xed, 0x81, 0xe3, 0xfe, 0xbc, 0xd4, 0x9d, 0x2a, 0xf1, 0x96, 0xcc,
	0x41, 0x6b, 0x26, 0xf8, 0x22, 0x91, 0x30, 0xcb, 0xfc, 0xce, 0x19, 0x69, 0x2d, 0x20, 0x96, 0x91,
	0x87, 0x70, 0xcb, 0x34, 0xa6, 0x1d, 0xb8, 0xd5, 0xa6, 0x61, 0xd7, 0xd2, 0x8e, 0x9d, 0x1e, 0x7c,
	0x54, 0xc9, 0xbf, 0xd1, 0x9e, 0xc9, 0x1c, 0xd4, 0x86, 0x05, 0x40, 0xaf, 0x48, 0x7d, 0xca, 0x78,
	0x48, 0xcd, 0x62, 0xe7, 0x1c, 0x15, 0xe3, 0xa1, 0x55, 0xba, 0x71, 0x2a, 0x74, 0x42, 0x9a, 0x7b,
	0x2a, 0xd4, 0x2e, 0x1a, 0xbf, 0x23, 0xb3, 0xba, 0x6e, 0x0e, 0xdc, 0xdd, 0x01, 0x77, 0xc7, 0x29,
	0x70, 0xa7, 0x42, 0x87, 0xa4, 0x35, 0x83, 0x58, 0x6c, 0x60, 0x9b, 0x55, 0x7e, 0x4e, 0x79, 0xc6,
	0x98, 0x74, 0x1e, 0xc0, 0xd7, 0x22, 0x78, 0x01, 0xbc, 0x03, 0xad, 0xbd, 0x10, 0xe8, 0xff, 0x62,
	0xce, 0x30, 0x41, 0xd0, 0xbf, 0xc4, 0xdc, 0x90, 0xd6, 0x04, 0x70, 0x87, 0x55, 0xd3, 0x12, 0xa7,
	0x75, 0x5c, 0x8c, 0x3e, 0x7c, 0x0b, 0xa7, 0x32, 0x3c, 0x25, 0x27, 0x1c, 0x30, 0xb3, 0x9d, 0x1f,
	0xda, 0xbe, 0x7e, 0xe6, 0x63, 0xcd, 0x93, 0xcc, 0x6f, 0x64, 0xc9, 0x17, 0x9f, 0x01, 0x00, 0x00,
	0xff, 0xff, 0x0f, 0x90, 0x67, 0x52, 0xb3, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ControllerServiceClient is the client API for ControllerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ControllerServiceClient interface {
	Ping(ctx context.Context, in *String, opts ...grpc.CallOption) (*String, error)
	NewClient(ctx context.Context, in *NewClientParam, opts ...grpc.CallOption) (*empty.Empty, error)
	RemoveClient(ctx context.Context, in *String, opts ...grpc.CallOption) (*empty.Empty, error)
	WebsocketMessage(ctx context.Context, in *Bytes, opts ...grpc.CallOption) (*empty.Empty, error)
	GetTemplates(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*TemplateList, error)
}

type controllerServiceClient struct {
	cc *grpc.ClientConn
}

func NewControllerServiceClient(cc *grpc.ClientConn) ControllerServiceClient {
	return &controllerServiceClient{cc}
}

func (c *controllerServiceClient) Ping(ctx context.Context, in *String, opts ...grpc.CallOption) (*String, error) {
	out := new(String)
	err := c.cc.Invoke(ctx, "/info_age.bremote.ControllerService/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerServiceClient) NewClient(ctx context.Context, in *NewClientParam, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/info_age.bremote.ControllerService/NewClient", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerServiceClient) RemoveClient(ctx context.Context, in *String, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/info_age.bremote.ControllerService/RemoveClient", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerServiceClient) WebsocketMessage(ctx context.Context, in *Bytes, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/info_age.bremote.ControllerService/WebsocketMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerServiceClient) GetTemplates(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*TemplateList, error) {
	out := new(TemplateList)
	err := c.cc.Invoke(ctx, "/info_age.bremote.ControllerService/GetTemplates", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ControllerServiceServer is the server API for ControllerService service.
type ControllerServiceServer interface {
	Ping(context.Context, *String) (*String, error)
	NewClient(context.Context, *NewClientParam) (*empty.Empty, error)
	RemoveClient(context.Context, *String) (*empty.Empty, error)
	WebsocketMessage(context.Context, *Bytes) (*empty.Empty, error)
	GetTemplates(context.Context, *empty.Empty) (*TemplateList, error)
}

// UnimplementedControllerServiceServer can be embedded to have forward compatible implementations.
type UnimplementedControllerServiceServer struct {
}

func (*UnimplementedControllerServiceServer) Ping(ctx context.Context, req *String) (*String, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (*UnimplementedControllerServiceServer) NewClient(ctx context.Context, req *NewClientParam) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NewClient not implemented")
}
func (*UnimplementedControllerServiceServer) RemoveClient(ctx context.Context, req *String) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveClient not implemented")
}
func (*UnimplementedControllerServiceServer) WebsocketMessage(ctx context.Context, req *Bytes) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WebsocketMessage not implemented")
}
func (*UnimplementedControllerServiceServer) GetTemplates(ctx context.Context, req *empty.Empty) (*TemplateList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTemplates not implemented")
}

func RegisterControllerServiceServer(s *grpc.Server, srv ControllerServiceServer) {
	s.RegisterService(&_ControllerService_serviceDesc, srv)
}

func _ControllerService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(String)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/info_age.bremote.ControllerService/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServiceServer).Ping(ctx, req.(*String))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControllerService_NewClient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewClientParam)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServiceServer).NewClient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/info_age.bremote.ControllerService/NewClient",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServiceServer).NewClient(ctx, req.(*NewClientParam))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControllerService_RemoveClient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(String)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServiceServer).RemoveClient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/info_age.bremote.ControllerService/RemoveClient",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServiceServer).RemoveClient(ctx, req.(*String))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControllerService_WebsocketMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Bytes)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServiceServer).WebsocketMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/info_age.bremote.ControllerService/WebsocketMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServiceServer).WebsocketMessage(ctx, req.(*Bytes))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControllerService_GetTemplates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServiceServer).GetTemplates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/info_age.bremote.ControllerService/GetTemplates",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServiceServer).GetTemplates(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _ControllerService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "info_age.bremote.ControllerService",
	HandlerType: (*ControllerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _ControllerService_Ping_Handler,
		},
		{
			MethodName: "NewClient",
			Handler:    _ControllerService_NewClient_Handler,
		},
		{
			MethodName: "RemoveClient",
			Handler:    _ControllerService_RemoveClient_Handler,
		},
		{
			MethodName: "WebsocketMessage",
			Handler:    _ControllerService_WebsocketMessage_Handler,
		},
		{
			MethodName: "GetTemplates",
			Handler:    _ControllerService_GetTemplates_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "controller.proto",
}
