// Code generated by protoc-gen-go. DO NOT EDIT.
// source: http.proto

package info_age_bremote

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type HTTPRequest struct {
	Method               string    `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Url                  string    `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Headers              []*Header `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty"`
	Body                 []byte    `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *HTTPRequest) Reset()         { *m = HTTPRequest{} }
func (m *HTTPRequest) String() string { return proto.CompactTextString(m) }
func (*HTTPRequest) ProtoMessage()    {}
func (*HTTPRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_11b04836674e6f94, []int{0}
}

func (m *HTTPRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HTTPRequest.Unmarshal(m, b)
}
func (m *HTTPRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HTTPRequest.Marshal(b, m, deterministic)
}
func (m *HTTPRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HTTPRequest.Merge(m, src)
}
func (m *HTTPRequest) XXX_Size() int {
	return xxx_messageInfo_HTTPRequest.Size(m)
}
func (m *HTTPRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HTTPRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HTTPRequest proto.InternalMessageInfo

func (m *HTTPRequest) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *HTTPRequest) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *HTTPRequest) GetHeaders() []*Header {
	if m != nil {
		return m.Headers
	}
	return nil
}

func (m *HTTPRequest) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

type HTTPResponse struct {
	Code                 int32     `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Headers              []*Header `protobuf:"bytes,2,rep,name=headers,proto3" json:"headers,omitempty"`
	Body                 []byte    `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *HTTPResponse) Reset()         { *m = HTTPResponse{} }
func (m *HTTPResponse) String() string { return proto.CompactTextString(m) }
func (*HTTPResponse) ProtoMessage()    {}
func (*HTTPResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_11b04836674e6f94, []int{1}
}

func (m *HTTPResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HTTPResponse.Unmarshal(m, b)
}
func (m *HTTPResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HTTPResponse.Marshal(b, m, deterministic)
}
func (m *HTTPResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HTTPResponse.Merge(m, src)
}
func (m *HTTPResponse) XXX_Size() int {
	return xxx_messageInfo_HTTPResponse.Size(m)
}
func (m *HTTPResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HTTPResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HTTPResponse proto.InternalMessageInfo

func (m *HTTPResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *HTTPResponse) GetHeaders() []*Header {
	if m != nil {
		return m.Headers
	}
	return nil
}

func (m *HTTPResponse) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

type Header struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Values               []string `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Header) Reset()         { *m = Header{} }
func (m *Header) String() string { return proto.CompactTextString(m) }
func (*Header) ProtoMessage()    {}
func (*Header) Descriptor() ([]byte, []int) {
	return fileDescriptor_11b04836674e6f94, []int{2}
}

func (m *Header) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Header.Unmarshal(m, b)
}
func (m *Header) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Header.Marshal(b, m, deterministic)
}
func (m *Header) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Header.Merge(m, src)
}
func (m *Header) XXX_Size() int {
	return xxx_messageInfo_Header.Size(m)
}
func (m *Header) XXX_DiscardUnknown() {
	xxx_messageInfo_Header.DiscardUnknown(m)
}

var xxx_messageInfo_Header proto.InternalMessageInfo

func (m *Header) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Header) GetValues() []string {
	if m != nil {
		return m.Values
	}
	return nil
}

func init() {
	proto.RegisterType((*HTTPRequest)(nil), "info_age.bremote.HTTPRequest")
	proto.RegisterType((*HTTPResponse)(nil), "info_age.bremote.HTTPResponse")
	proto.RegisterType((*Header)(nil), "info_age.bremote.Header")
}

func init() { proto.RegisterFile("http.proto", fileDescriptor_11b04836674e6f94) }

var fileDescriptor_11b04836674e6f94 = []byte{
	// 247 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x91, 0x31, 0x4f, 0xc3, 0x30,
	0x10, 0x85, 0x49, 0x53, 0x82, 0x7a, 0xed, 0x50, 0xdd, 0x80, 0x2c, 0x24, 0x50, 0x94, 0x29, 0x53,
	0x86, 0xf0, 0x13, 0x58, 0xc2, 0x86, 0x4c, 0x07, 0x36, 0x94, 0xe0, 0x83, 0x14, 0xd2, 0x5c, 0xb0,
	0x9d, 0x4a, 0x9d, 0xf8, 0xeb, 0xc8, 0x76, 0x10, 0x15, 0x82, 0x81, 0xed, 0x9d, 0xfd, 0xe4, 0xef,
	0xde, 0x33, 0x40, 0x6b, 0xed, 0x50, 0x0c, 0x9a, 0x2d, 0xe3, 0x7a, 0xdb, 0x3f, 0xf3, 0x63, 0xfd,
	0x42, 0x45, 0xa3, 0x69, 0xc7, 0x96, 0xb2, 0x0f, 0x58, 0x56, 0x9b, 0xcd, 0x9d, 0xa4, 0xf7, 0x91,
	0x8c, 0xc5, 0x73, 0x48, 0x76, 0x64, 0x5b, 0x56, 0x22, 0x4a, 0xa3, 0x7c, 0x21, 0xa7, 0x09, 0xd7,
	0x10, 0x8f, 0xba, 0x13, 0x33, 0x7f, 0xe8, 0x24, 0x96, 0x70, 0xd6, 0x52, 0xad, 0x48, 0x1b, 0x11,
	0xa7, 0x71, 0xbe, 0x2c, 0x45, 0xf1, 0xf3, 0xf1, 0xa2, 0xf2, 0x06, 0xf9, 0x65, 0x44, 0x84, 0x79,
	0xc3, 0xea, 0x20, 0xe6, 0x69, 0x94, 0xaf, 0xa4, 0xd7, 0xd9, 0x2b, 0xac, 0xc2, 0x02, 0x66, 0xe0,
	0xde, 0x90, 0xf3, 0xdc, 0xb0, 0x22, 0xcf, 0x3f, 0x95, 0x5e, 0x1f, 0xb3, 0x66, 0xff, 0x65, 0xc5,
	0x47, 0xac, 0x12, 0x92, 0x60, 0x73, 0x79, 0xde, 0xe8, 0x30, 0x85, 0x74, 0xd2, 0x25, 0xdf, 0xd7,
	0xdd, 0x48, 0x01, 0xb1, 0x90, 0xd3, 0x54, 0x3e, 0x84, 0x82, 0xee, 0x49, 0xef, 0xb7, 0x4f, 0x84,
	0xb7, 0x90, 0x54, 0x75, 0xaf, 0x3a, 0xc2, 0xcb, 0x5f, 0x76, 0xf8, 0x6e, 0xf2, 0xe2, 0xea, 0xaf,
	0xeb, 0x90, 0x33, 0x3b, 0x69, 0x12, 0xff, 0x27, 0xd7, 0x9f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xf3,
	0x19, 0x58, 0xa0, 0xa1, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// HTTPServiceClient is the client API for HTTPService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type HTTPServiceClient interface {
	Handle(ctx context.Context, in *HTTPRequest, opts ...grpc.CallOption) (*HTTPResponse, error)
}

type hTTPServiceClient struct {
	cc *grpc.ClientConn
}

func NewHTTPServiceClient(cc *grpc.ClientConn) HTTPServiceClient {
	return &hTTPServiceClient{cc}
}

func (c *hTTPServiceClient) Handle(ctx context.Context, in *HTTPRequest, opts ...grpc.CallOption) (*HTTPResponse, error) {
	out := new(HTTPResponse)
	err := c.cc.Invoke(ctx, "/info_age.bremote.HTTPService/Handle", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HTTPServiceServer is the server API for HTTPService service.
type HTTPServiceServer interface {
	Handle(context.Context, *HTTPRequest) (*HTTPResponse, error)
}

// UnimplementedHTTPServiceServer can be embedded to have forward compatible implementations.
type UnimplementedHTTPServiceServer struct {
}

func (*UnimplementedHTTPServiceServer) Handle(ctx context.Context, req *HTTPRequest) (*HTTPResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Handle not implemented")
}

func RegisterHTTPServiceServer(s *grpc.Server, srv HTTPServiceServer) {
	s.RegisterService(&_HTTPService_serviceDesc, srv)
}

func _HTTPService_Handle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HTTPRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HTTPServiceServer).Handle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/info_age.bremote.HTTPService/Handle",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HTTPServiceServer).Handle(ctx, req.(*HTTPRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _HTTPService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "info_age.bremote.HTTPService",
	HandlerType: (*HTTPServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Handle",
			Handler:    _HTTPService_Handle_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "http.proto",
}
