// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proxy.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type InitParam struct {
	Instance             string           `protobuf:"bytes,1,opt,name=instance,proto3" json:"instance,omitempty"`
	SessionType          ProxySessionType `protobuf:"varint,2,opt,name=sessionType,proto3,enum=info_age.bremote.ProxySessionType" json:"sessionType,omitempty"`
	Status               string           `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *InitParam) Reset()         { *m = InitParam{} }
func (m *InitParam) String() string { return proto.CompactTextString(m) }
func (*InitParam) ProtoMessage()    {}
func (*InitParam) Descriptor() ([]byte, []int) {
	return fileDescriptor_700b50b08ed8dbaf, []int{0}
}

func (m *InitParam) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InitParam.Unmarshal(m, b)
}
func (m *InitParam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InitParam.Marshal(b, m, deterministic)
}
func (m *InitParam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InitParam.Merge(m, src)
}
func (m *InitParam) XXX_Size() int {
	return xxx_messageInfo_InitParam.Size(m)
}
func (m *InitParam) XXX_DiscardUnknown() {
	xxx_messageInfo_InitParam.DiscardUnknown(m)
}

var xxx_messageInfo_InitParam proto.InternalMessageInfo

func (m *InitParam) GetInstance() string {
	if m != nil {
		return m.Instance
	}
	return ""
}

func (m *InitParam) GetSessionType() ProxySessionType {
	if m != nil {
		return m.SessionType
	}
	return ProxySessionType_Undefined
}

func (m *InitParam) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type ProxyClientList struct {
	Clients              []*ProxyClient `protobuf:"bytes,1,rep,name=clients,proto3" json:"clients,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ProxyClientList) Reset()         { *m = ProxyClientList{} }
func (m *ProxyClientList) String() string { return proto.CompactTextString(m) }
func (*ProxyClientList) ProtoMessage()    {}
func (*ProxyClientList) Descriptor() ([]byte, []int) {
	return fileDescriptor_700b50b08ed8dbaf, []int{1}
}

func (m *ProxyClientList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProxyClientList.Unmarshal(m, b)
}
func (m *ProxyClientList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProxyClientList.Marshal(b, m, deterministic)
}
func (m *ProxyClientList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProxyClientList.Merge(m, src)
}
func (m *ProxyClientList) XXX_Size() int {
	return xxx_messageInfo_ProxyClientList.Size(m)
}
func (m *ProxyClientList) XXX_DiscardUnknown() {
	xxx_messageInfo_ProxyClientList.DiscardUnknown(m)
}

var xxx_messageInfo_ProxyClientList proto.InternalMessageInfo

func (m *ProxyClientList) GetClients() []*ProxyClient {
	if m != nil {
		return m.Clients
	}
	return nil
}

type GetClientsParam struct {
	WithStatus           bool     `protobuf:"varint,1,opt,name=withStatus,proto3" json:"withStatus,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetClientsParam) Reset()         { *m = GetClientsParam{} }
func (m *GetClientsParam) String() string { return proto.CompactTextString(m) }
func (*GetClientsParam) ProtoMessage()    {}
func (*GetClientsParam) Descriptor() ([]byte, []int) {
	return fileDescriptor_700b50b08ed8dbaf, []int{2}
}

func (m *GetClientsParam) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetClientsParam.Unmarshal(m, b)
}
func (m *GetClientsParam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetClientsParam.Marshal(b, m, deterministic)
}
func (m *GetClientsParam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetClientsParam.Merge(m, src)
}
func (m *GetClientsParam) XXX_Size() int {
	return xxx_messageInfo_GetClientsParam.Size(m)
}
func (m *GetClientsParam) XXX_DiscardUnknown() {
	xxx_messageInfo_GetClientsParam.DiscardUnknown(m)
}

var xxx_messageInfo_GetClientsParam proto.InternalMessageInfo

func (m *GetClientsParam) GetWithStatus() bool {
	if m != nil {
		return m.WithStatus
	}
	return false
}

func init() {
	proto.RegisterType((*InitParam)(nil), "info_age.bremote.InitParam")
	proto.RegisterType((*ProxyClientList)(nil), "info_age.bremote.ProxyClientList")
	proto.RegisterType((*GetClientsParam)(nil), "info_age.bremote.GetClientsParam")
}

func init() { proto.RegisterFile("proxy.proto", fileDescriptor_700b50b08ed8dbaf) }

var fileDescriptor_700b50b08ed8dbaf = []byte{
	// 333 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x52, 0x4d, 0x4f, 0xc2, 0x40,
	0x10, 0xa5, 0x42, 0x10, 0xa6, 0x46, 0xcc, 0x1e, 0x48, 0xb3, 0x44, 0x03, 0x3d, 0x71, 0x71, 0x89,
	0x78, 0xf0, 0xa2, 0x17, 0x3f, 0x62, 0x34, 0x1e, 0x48, 0xf1, 0xe4, 0xc5, 0x14, 0x32, 0xd4, 0x4d,
	0x60, 0xb7, 0xe9, 0x0e, 0x2a, 0x3f, 0xc0, 0xdf, 0xe9, 0x5f, 0x31, 0xdd, 0xe5, 0x2b, 0x34, 0x78,
	0x7c, 0x3b, 0x6f, 0xe6, 0xcd, 0x7b, 0xb3, 0xe0, 0xa7, 0x99, 0xfe, 0x5e, 0x88, 0x34, 0xd3, 0xa4,
	0xd9, 0x89, 0x54, 0x13, 0xfd, 0x1e, 0x27, 0x28, 0x46, 0x19, 0xce, 0x34, 0x21, 0x6f, 0x25, 0x5a,
	0x27, 0x53, 0xec, 0xd9, 0xfa, 0x68, 0x3e, 0xe9, 0xe1, 0x2c, 0xa5, 0x25, 0x9d, 0xfb, 0xb4, 0x48,
	0xd1, 0x38, 0x10, 0xfe, 0x78, 0x50, 0x7f, 0x52, 0x92, 0x06, 0x71, 0x16, 0xcf, 0x18, 0x87, 0x9a,
	0x54, 0x86, 0x62, 0x35, 0xc6, 0xc0, 0x6b, 0x7b, 0xdd, 0x7a, 0xb4, 0xc6, 0xec, 0x1e, 0x7c, 0x83,
	0xc6, 0x48, 0xad, 0x5e, 0x17, 0x29, 0x06, 0x07, 0x6d, 0xaf, 0x7b, 0xdc, 0x0f, 0xc5, 0xae, 0xb6,
	0x18, 0xe4, 0x9b, 0x0d, 0x37, 0xcc, 0x68, 0xbb, 0x8d, 0x35, 0xa1, 0x6a, 0x28, 0xa6, 0xb9, 0x09,
	0xca, 0x76, 0xfe, 0x12, 0x85, 0xcf, 0xd0, 0xb0, 0x8d, 0x77, 0x53, 0x89, 0x8a, 0x5e, 0xa4, 0x21,
	0x76, 0x05, 0x87, 0x63, 0x8b, 0x4c, 0xe0, 0xb5, 0xcb, 0x5d, 0xbf, 0x7f, 0xba, 0x47, 0xcc, 0xf5,
	0x44, 0x2b, 0x76, 0x78, 0x01, 0x8d, 0x47, 0x24, 0xf7, 0x6a, 0x9c, 0xb1, 0x33, 0x80, 0x2f, 0x49,
	0x1f, 0x43, 0x27, 0x9d, 0x5b, 0xab, 0x45, 0x5b, 0x2f, 0xfd, 0x5f, 0x0f, 0x8e, 0x96, 0x8b, 0x67,
	0x9f, 0x72, 0x8c, 0xec, 0x1a, 0x2a, 0x03, 0xa9, 0x12, 0x16, 0x14, 0x35, 0x87, 0x94, 0x49, 0x95,
	0xf0, 0xbd, 0x95, 0xb0, 0xc4, 0x6e, 0xa0, 0x92, 0x87, 0xca, 0x5a, 0x45, 0xce, 0x3a, 0x6c, 0xde,
	0x14, 0xee, 0x4a, 0x62, 0x75, 0x25, 0xf1, 0x90, 0x5f, 0x29, 0x2c, 0xb1, 0x08, 0x60, 0x63, 0x80,
	0x75, 0x8a, 0x43, 0x76, 0xec, 0xf1, 0xce, 0xbf, 0xc9, 0xe4, 0x69, 0xde, 0x76, 0x80, 0x2b, 0x24,
	0xcb, 0x3b, 0xdf, 0xe6, 0xd9, 0x8f, 0xf4, 0x56, 0x8e, 0x53, 0x39, 0xaa, 0xda, 0x45, 0x2e, 0xff,
	0x02, 0x00, 0x00, 0xff, 0xff, 0x34, 0x9c, 0x68, 0x5c, 0x5d, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ProxyServiceClient is the client API for ProxyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ProxyServiceClient interface {
	Ping(ctx context.Context, in *String, opts ...grpc.CallOption) (*String, error)
	Init(ctx context.Context, in *InitParam, opts ...grpc.CallOption) (*empty.Empty, error)
	GetClients(ctx context.Context, in *GetClientsParam, opts ...grpc.CallOption) (*ProxyClientList, error)
}

type proxyServiceClient struct {
	cc *grpc.ClientConn
}

func NewProxyServiceClient(cc *grpc.ClientConn) ProxyServiceClient {
	return &proxyServiceClient{cc}
}

func (c *proxyServiceClient) Ping(ctx context.Context, in *String, opts ...grpc.CallOption) (*String, error) {
	out := new(String)
	err := c.cc.Invoke(ctx, "/info_age.bremote.ProxyService/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *proxyServiceClient) Init(ctx context.Context, in *InitParam, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/info_age.bremote.ProxyService/Init", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *proxyServiceClient) GetClients(ctx context.Context, in *GetClientsParam, opts ...grpc.CallOption) (*ProxyClientList, error) {
	out := new(ProxyClientList)
	err := c.cc.Invoke(ctx, "/info_age.bremote.ProxyService/GetClients", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProxyServiceServer is the server API for ProxyService service.
type ProxyServiceServer interface {
	Ping(context.Context, *String) (*String, error)
	Init(context.Context, *InitParam) (*empty.Empty, error)
	GetClients(context.Context, *GetClientsParam) (*ProxyClientList, error)
}

// UnimplementedProxyServiceServer can be embedded to have forward compatible implementations.
type UnimplementedProxyServiceServer struct {
}

func (*UnimplementedProxyServiceServer) Ping(ctx context.Context, req *String) (*String, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (*UnimplementedProxyServiceServer) Init(ctx context.Context, req *InitParam) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Init not implemented")
}
func (*UnimplementedProxyServiceServer) GetClients(ctx context.Context, req *GetClientsParam) (*ProxyClientList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetClients not implemented")
}

func RegisterProxyServiceServer(s *grpc.Server, srv ProxyServiceServer) {
	s.RegisterService(&_ProxyService_serviceDesc, srv)
}

func _ProxyService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(String)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProxyServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/info_age.bremote.ProxyService/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProxyServiceServer).Ping(ctx, req.(*String))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProxyService_Init_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitParam)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProxyServiceServer).Init(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/info_age.bremote.ProxyService/Init",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProxyServiceServer).Init(ctx, req.(*InitParam))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProxyService_GetClients_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetClientsParam)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProxyServiceServer).GetClients(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/info_age.bremote.ProxyService/GetClients",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProxyServiceServer).GetClients(ctx, req.(*GetClientsParam))
	}
	return interceptor(ctx, in, info, handler)
}

var _ProxyService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "info_age.bremote.ProxyService",
	HandlerType: (*ProxyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _ProxyService_Ping_Handler,
		},
		{
			MethodName: "Init",
			Handler:    _ProxyService_Init_Handler,
		},
		{
			MethodName: "GetClients",
			Handler:    _ProxyService_GetClients_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proxy.proto",
}
