// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proxy.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type InitParam struct {
	Instance             string           `protobuf:"bytes,1,opt,name=instance,proto3" json:"instance,omitempty"`
	SessionType          ProxySessionType `protobuf:"varint,2,opt,name=sessionType,proto3,enum=info_age.bremote.ProxySessionType" json:"sessionType,omitempty"`
	Status               string           `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	HttpAddr             string           `protobuf:"bytes,4,opt,name=httpAddr,proto3" json:"httpAddr,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *InitParam) Reset()         { *m = InitParam{} }
func (m *InitParam) String() string { return proto.CompactTextString(m) }
func (*InitParam) ProtoMessage()    {}
func (*InitParam) Descriptor() ([]byte, []int) {
	return fileDescriptor_700b50b08ed8dbaf, []int{0}
}

func (m *InitParam) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InitParam.Unmarshal(m, b)
}
func (m *InitParam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InitParam.Marshal(b, m, deterministic)
}
func (m *InitParam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InitParam.Merge(m, src)
}
func (m *InitParam) XXX_Size() int {
	return xxx_messageInfo_InitParam.Size(m)
}
func (m *InitParam) XXX_DiscardUnknown() {
	xxx_messageInfo_InitParam.DiscardUnknown(m)
}

var xxx_messageInfo_InitParam proto.InternalMessageInfo

func (m *InitParam) GetInstance() string {
	if m != nil {
		return m.Instance
	}
	return ""
}

func (m *InitParam) GetSessionType() ProxySessionType {
	if m != nil {
		return m.SessionType
	}
	return ProxySessionType_Undefined
}

func (m *InitParam) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *InitParam) GetHttpAddr() string {
	if m != nil {
		return m.HttpAddr
	}
	return ""
}

type ProxyClientList struct {
	Clients              []*ProxyClient `protobuf:"bytes,1,rep,name=clients,proto3" json:"clients,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ProxyClientList) Reset()         { *m = ProxyClientList{} }
func (m *ProxyClientList) String() string { return proto.CompactTextString(m) }
func (*ProxyClientList) ProtoMessage()    {}
func (*ProxyClientList) Descriptor() ([]byte, []int) {
	return fileDescriptor_700b50b08ed8dbaf, []int{1}
}

func (m *ProxyClientList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProxyClientList.Unmarshal(m, b)
}
func (m *ProxyClientList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProxyClientList.Marshal(b, m, deterministic)
}
func (m *ProxyClientList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProxyClientList.Merge(m, src)
}
func (m *ProxyClientList) XXX_Size() int {
	return xxx_messageInfo_ProxyClientList.Size(m)
}
func (m *ProxyClientList) XXX_DiscardUnknown() {
	xxx_messageInfo_ProxyClientList.DiscardUnknown(m)
}

var xxx_messageInfo_ProxyClientList proto.InternalMessageInfo

func (m *ProxyClientList) GetClients() []*ProxyClient {
	if m != nil {
		return m.Clients
	}
	return nil
}

type GetClientsParam struct {
	WithStatus           bool     `protobuf:"varint,1,opt,name=withStatus,proto3" json:"withStatus,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetClientsParam) Reset()         { *m = GetClientsParam{} }
func (m *GetClientsParam) String() string { return proto.CompactTextString(m) }
func (*GetClientsParam) ProtoMessage()    {}
func (*GetClientsParam) Descriptor() ([]byte, []int) {
	return fileDescriptor_700b50b08ed8dbaf, []int{2}
}

func (m *GetClientsParam) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetClientsParam.Unmarshal(m, b)
}
func (m *GetClientsParam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetClientsParam.Marshal(b, m, deterministic)
}
func (m *GetClientsParam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetClientsParam.Merge(m, src)
}
func (m *GetClientsParam) XXX_Size() int {
	return xxx_messageInfo_GetClientsParam.Size(m)
}
func (m *GetClientsParam) XXX_DiscardUnknown() {
	xxx_messageInfo_GetClientsParam.DiscardUnknown(m)
}

var xxx_messageInfo_GetClientsParam proto.InternalMessageInfo

func (m *GetClientsParam) GetWithStatus() bool {
	if m != nil {
		return m.WithStatus
	}
	return false
}

type GroupInstanceMessage struct {
	Group                string   `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	Instance             string   `protobuf:"bytes,2,opt,name=instance,proto3" json:"instance,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GroupInstanceMessage) Reset()         { *m = GroupInstanceMessage{} }
func (m *GroupInstanceMessage) String() string { return proto.CompactTextString(m) }
func (*GroupInstanceMessage) ProtoMessage()    {}
func (*GroupInstanceMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_700b50b08ed8dbaf, []int{3}
}

func (m *GroupInstanceMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupInstanceMessage.Unmarshal(m, b)
}
func (m *GroupInstanceMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupInstanceMessage.Marshal(b, m, deterministic)
}
func (m *GroupInstanceMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupInstanceMessage.Merge(m, src)
}
func (m *GroupInstanceMessage) XXX_Size() int {
	return xxx_messageInfo_GroupInstanceMessage.Size(m)
}
func (m *GroupInstanceMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupInstanceMessage.DiscardUnknown(m)
}

var xxx_messageInfo_GroupInstanceMessage proto.InternalMessageInfo

func (m *GroupInstanceMessage) GetGroup() string {
	if m != nil {
		return m.Group
	}
	return ""
}

func (m *GroupInstanceMessage) GetInstance() string {
	if m != nil {
		return m.Instance
	}
	return ""
}

type GroupListMessage struct {
	Groups               []string `protobuf:"bytes,1,rep,name=groups,proto3" json:"groups,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GroupListMessage) Reset()         { *m = GroupListMessage{} }
func (m *GroupListMessage) String() string { return proto.CompactTextString(m) }
func (*GroupListMessage) ProtoMessage()    {}
func (*GroupListMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_700b50b08ed8dbaf, []int{4}
}

func (m *GroupListMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupListMessage.Unmarshal(m, b)
}
func (m *GroupListMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupListMessage.Marshal(b, m, deterministic)
}
func (m *GroupListMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupListMessage.Merge(m, src)
}
func (m *GroupListMessage) XXX_Size() int {
	return xxx_messageInfo_GroupListMessage.Size(m)
}
func (m *GroupListMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupListMessage.DiscardUnknown(m)
}

var xxx_messageInfo_GroupListMessage proto.InternalMessageInfo

func (m *GroupListMessage) GetGroups() []string {
	if m != nil {
		return m.Groups
	}
	return nil
}

type MemberListMessage struct {
	Instances            []string `protobuf:"bytes,1,rep,name=instances,proto3" json:"instances,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MemberListMessage) Reset()         { *m = MemberListMessage{} }
func (m *MemberListMessage) String() string { return proto.CompactTextString(m) }
func (*MemberListMessage) ProtoMessage()    {}
func (*MemberListMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_700b50b08ed8dbaf, []int{5}
}

func (m *MemberListMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MemberListMessage.Unmarshal(m, b)
}
func (m *MemberListMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MemberListMessage.Marshal(b, m, deterministic)
}
func (m *MemberListMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MemberListMessage.Merge(m, src)
}
func (m *MemberListMessage) XXX_Size() int {
	return xxx_messageInfo_MemberListMessage.Size(m)
}
func (m *MemberListMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_MemberListMessage.DiscardUnknown(m)
}

var xxx_messageInfo_MemberListMessage proto.InternalMessageInfo

func (m *MemberListMessage) GetInstances() []string {
	if m != nil {
		return m.Instances
	}
	return nil
}

type KVKeyMessage struct {
	Client               string   `protobuf:"bytes,1,opt,name=client,proto3" json:"client,omitempty"`
	Key                  string   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KVKeyMessage) Reset()         { *m = KVKeyMessage{} }
func (m *KVKeyMessage) String() string { return proto.CompactTextString(m) }
func (*KVKeyMessage) ProtoMessage()    {}
func (*KVKeyMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_700b50b08ed8dbaf, []int{6}
}

func (m *KVKeyMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KVKeyMessage.Unmarshal(m, b)
}
func (m *KVKeyMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KVKeyMessage.Marshal(b, m, deterministic)
}
func (m *KVKeyMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KVKeyMessage.Merge(m, src)
}
func (m *KVKeyMessage) XXX_Size() int {
	return xxx_messageInfo_KVKeyMessage.Size(m)
}
func (m *KVKeyMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_KVKeyMessage.DiscardUnknown(m)
}

var xxx_messageInfo_KVKeyMessage proto.InternalMessageInfo

func (m *KVKeyMessage) GetClient() string {
	if m != nil {
		return m.Client
	}
	return ""
}

func (m *KVKeyMessage) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type KVSetValueMessage struct {
	Key                  *KVKeyMessage `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                string        `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *KVSetValueMessage) Reset()         { *m = KVSetValueMessage{} }
func (m *KVSetValueMessage) String() string { return proto.CompactTextString(m) }
func (*KVSetValueMessage) ProtoMessage()    {}
func (*KVSetValueMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_700b50b08ed8dbaf, []int{7}
}

func (m *KVSetValueMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KVSetValueMessage.Unmarshal(m, b)
}
func (m *KVSetValueMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KVSetValueMessage.Marshal(b, m, deterministic)
}
func (m *KVSetValueMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KVSetValueMessage.Merge(m, src)
}
func (m *KVSetValueMessage) XXX_Size() int {
	return xxx_messageInfo_KVSetValueMessage.Size(m)
}
func (m *KVSetValueMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_KVSetValueMessage.DiscardUnknown(m)
}

var xxx_messageInfo_KVSetValueMessage proto.InternalMessageInfo

func (m *KVSetValueMessage) GetKey() *KVKeyMessage {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *KVSetValueMessage) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type KVSetValueListMessage struct {
	Data                 []*KVSetValueMessage `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *KVSetValueListMessage) Reset()         { *m = KVSetValueListMessage{} }
func (m *KVSetValueListMessage) String() string { return proto.CompactTextString(m) }
func (*KVSetValueListMessage) ProtoMessage()    {}
func (*KVSetValueListMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_700b50b08ed8dbaf, []int{8}
}

func (m *KVSetValueListMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KVSetValueListMessage.Unmarshal(m, b)
}
func (m *KVSetValueListMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KVSetValueListMessage.Marshal(b, m, deterministic)
}
func (m *KVSetValueListMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KVSetValueListMessage.Merge(m, src)
}
func (m *KVSetValueListMessage) XXX_Size() int {
	return xxx_messageInfo_KVSetValueListMessage.Size(m)
}
func (m *KVSetValueListMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_KVSetValueListMessage.DiscardUnknown(m)
}

var xxx_messageInfo_KVSetValueListMessage proto.InternalMessageInfo

func (m *KVSetValueListMessage) GetData() []*KVSetValueMessage {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*InitParam)(nil), "info_age.bremote.InitParam")
	proto.RegisterType((*ProxyClientList)(nil), "info_age.bremote.ProxyClientList")
	proto.RegisterType((*GetClientsParam)(nil), "info_age.bremote.GetClientsParam")
	proto.RegisterType((*GroupInstanceMessage)(nil), "info_age.bremote.GroupInstanceMessage")
	proto.RegisterType((*GroupListMessage)(nil), "info_age.bremote.GroupListMessage")
	proto.RegisterType((*MemberListMessage)(nil), "info_age.bremote.MemberListMessage")
	proto.RegisterType((*KVKeyMessage)(nil), "info_age.bremote.KVKeyMessage")
	proto.RegisterType((*KVSetValueMessage)(nil), "info_age.bremote.KVSetValueMessage")
	proto.RegisterType((*KVSetValueListMessage)(nil), "info_age.bremote.KVSetValueListMessage")
}

func init() { proto.RegisterFile("proxy.proto", fileDescriptor_700b50b08ed8dbaf) }

var fileDescriptor_700b50b08ed8dbaf = []byte{
	// 663 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x95, 0xdd, 0x4e, 0x13, 0x41,
	0x14, 0xc7, 0x5b, 0x5a, 0x91, 0x9e, 0x25, 0xb6, 0x8c, 0x88, 0xcd, 0xa2, 0x04, 0xc6, 0x44, 0x89,
	0x89, 0x8b, 0xd4, 0x0b, 0xbc, 0xd0, 0x0b, 0x10, 0x52, 0xb1, 0x62, 0x9a, 0x2d, 0x29, 0x46, 0x2f,
	0xcc, 0xb6, 0x3d, 0x2c, 0x1b, 0xda, 0x9d, 0xcd, 0xce, 0x14, 0xed, 0xe3, 0xf8, 0x4e, 0x3e, 0x90,
	0x99, 0x8f, 0x6d, 0x97, 0x96, 0xae, 0xbd, 0xf0, 0xae, 0x67, 0xe6, 0x9c, 0xdf, 0xf9, 0x98, 0xff,
	0xe9, 0x82, 0x15, 0xc5, 0xec, 0xd7, 0xc8, 0x89, 0x62, 0x26, 0x18, 0xa9, 0x04, 0xe1, 0x25, 0xfb,
	0xe1, 0xf9, 0xe8, 0x74, 0x62, 0x1c, 0x30, 0x81, 0xf6, 0xa6, 0xcf, 0x98, 0xdf, 0xc7, 0x3d, 0x75,
	0xdf, 0x19, 0x5e, 0xee, 0xe1, 0x20, 0x12, 0xc6, 0xdd, 0xb6, 0xc4, 0x28, 0x42, 0xae, 0x0d, 0xfa,
	0x3b, 0x0f, 0xa5, 0xd3, 0x30, 0x10, 0x4d, 0x2f, 0xf6, 0x06, 0xc4, 0x86, 0x95, 0x20, 0xe4, 0xc2,
	0x0b, 0xbb, 0x58, 0xcd, 0x6f, 0xe7, 0x77, 0x4b, 0xee, 0xd8, 0x26, 0xc7, 0x60, 0x71, 0xe4, 0x3c,
	0x60, 0xe1, 0xf9, 0x28, 0xc2, 0xea, 0xd2, 0x76, 0x7e, 0xf7, 0x41, 0x8d, 0x3a, 0xd3, 0xb9, 0x9d,
	0xa6, 0xac, 0xac, 0x35, 0xf1, 0x74, 0xd3, 0x61, 0x64, 0x03, 0x96, 0xb9, 0xf0, 0xc4, 0x90, 0x57,
	0x0b, 0x8a, 0x6f, 0x2c, 0x99, 0xf9, 0x4a, 0x88, 0xe8, 0xb0, 0xd7, 0x8b, 0xab, 0x45, 0x9d, 0x39,
	0xb1, 0xe9, 0x27, 0x28, 0x2b, 0xe8, 0x87, 0x7e, 0x80, 0xa1, 0xf8, 0x1c, 0x70, 0x41, 0x0e, 0xe0,
	0x7e, 0x57, 0x59, 0xbc, 0x9a, 0xdf, 0x2e, 0xec, 0x5a, 0xb5, 0xa7, 0x73, 0x0a, 0xd1, 0x31, 0x6e,
	0xe2, 0x4d, 0xf7, 0xa1, 0x5c, 0x47, 0xa1, 0x4f, 0xb9, 0x6e, 0x7a, 0x0b, 0xe0, 0x67, 0x20, 0xae,
	0x5a, 0xba, 0x2c, 0xd9, 0xf6, 0x8a, 0x9b, 0x3a, 0xa1, 0x1f, 0x61, 0xbd, 0x1e, 0xb3, 0x61, 0x74,
	0x6a, 0x26, 0x71, 0x86, 0x9c, 0x7b, 0x3e, 0x92, 0x75, 0xb8, 0xe7, 0xcb, 0x73, 0x33, 0x29, 0x6d,
	0xdc, 0x1a, 0xe1, 0xd2, 0xed, 0x11, 0xd2, 0x97, 0x50, 0x51, 0x24, 0xd9, 0x42, 0x42, 0xd9, 0x80,
	0x65, 0x15, 0xa8, 0x1b, 0x29, 0xb9, 0xc6, 0xa2, 0xfb, 0xb0, 0x76, 0x86, 0x83, 0x0e, 0xc6, 0x69,
	0xe7, 0x27, 0x50, 0x4a, 0x60, 0x89, 0xff, 0xe4, 0x80, 0xbe, 0x85, 0xd5, 0x46, 0xbb, 0x81, 0xa3,
	0x14, 0x5a, 0xb7, 0x6d, 0x2a, 0x34, 0x16, 0xa9, 0x40, 0xe1, 0x1a, 0x47, 0xa6, 0x3a, 0xf9, 0x93,
	0x7e, 0x87, 0xb5, 0x46, 0xbb, 0x85, 0xa2, 0xed, 0xf5, 0x87, 0xe3, 0xfe, 0x5e, 0x6b, 0x37, 0x19,
	0x6b, 0xd5, 0xb6, 0x66, 0xe7, 0x9b, 0xce, 0xa5, 0x30, 0x72, 0x22, 0x37, 0x92, 0x60, 0xd0, 0xda,
	0xa0, 0x4d, 0x78, 0x34, 0x81, 0xa7, 0xbb, 0x39, 0x80, 0x62, 0xcf, 0x13, 0x9e, 0x79, 0xc1, 0x67,
	0x77, 0x65, 0x98, 0xaa, 0xc9, 0x55, 0x01, 0xb5, 0x3f, 0x2b, 0xb0, 0x6a, 0x64, 0x16, 0xdf, 0x04,
	0x5d, 0x24, 0xef, 0xa0, 0xd8, 0x0c, 0x42, 0x9f, 0x54, 0x67, 0x19, 0x2d, 0x11, 0x07, 0xa1, 0x6f,
	0xcf, 0xbd, 0xa1, 0x39, 0xf2, 0x1e, 0x8a, 0x72, 0x05, 0xc8, 0xe6, 0xac, 0xcf, 0x78, 0x35, 0xec,
	0x0d, 0x47, 0xef, 0x94, 0x93, 0xec, 0x94, 0x73, 0x22, 0x77, 0x8a, 0xe6, 0x88, 0x0b, 0x30, 0x91,
	0x14, 0xd9, 0x99, 0x85, 0x4c, 0x09, 0xce, 0xde, 0xc9, 0xd4, 0xaa, 0xd2, 0xf7, 0x29, 0x94, 0xc6,
	0x4a, 0x21, 0x73, 0x52, 0xdb, 0x77, 0x2c, 0xdf, 0xb4, 0xbc, 0x68, 0x8e, 0x9c, 0x1b, 0xd1, 0x1d,
	0xf6, 0x7a, 0x89, 0x82, 0xc9, 0xf3, 0x39, 0x91, 0x53, 0x12, 0xcf, 0x68, 0xfa, 0x02, 0x1e, 0xaa,
	0x08, 0x17, 0x07, 0xec, 0x06, 0xff, 0x23, 0xd8, 0x85, 0xb2, 0x8a, 0xa8, 0xa3, 0xd0, 0xfa, 0xe7,
	0x19, 0xaf, 0x7a, 0x87, 0x66, 0x66, 0x96, 0x86, 0xe6, 0xc8, 0x21, 0x58, 0x8a, 0x79, 0x8c, 0x7d,
	0x14, 0x98, 0xc1, 0x9b, 0x5f, 0xd6, 0x09, 0x54, 0x2e, 0xb0, 0xc3, 0x59, 0xf7, 0x1a, 0xc7, 0xfa,
	0x7d, 0x3c, 0xcb, 0x39, 0x1a, 0x09, 0xe4, 0x19, 0x98, 0x26, 0x94, 0x1b, 0xed, 0x96, 0x60, 0x31,
	0x26, 0xca, 0x26, 0x8b, 0xe8, 0x3e, 0x83, 0x78, 0x36, 0x26, 0xd6, 0x13, 0xe2, 0x3f, 0x76, 0x35,
	0x73, 0x17, 0xbe, 0x00, 0x31, 0x38, 0x3d, 0xac, 0xc5, 0x88, 0x59, 0x0d, 0x5b, 0x86, 0x97, 0x29,
	0xe5, 0x17, 0x59, 0x43, 0xb8, 0xfd, 0x98, 0x5f, 0xd5, 0x7f, 0x95, 0x24, 0xa6, 0xf6, 0x65, 0xfe,
	0x93, 0x2e, 0x4e, 0x3e, 0xda, 0x01, 0x3b, 0x44, 0xa1, 0xfc, 0x5f, 0xa5, 0xfd, 0xd5, 0xb7, 0xf6,
	0x5b, 0xc1, 0x8b, 0x82, 0xce, 0xb2, 0xaa, 0xfb, 0xcd, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xbe,
	0x7e, 0xc4, 0x17, 0x80, 0x07, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ProxyServiceClient is the client API for ProxyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ProxyServiceClient interface {
	Ping(ctx context.Context, in *String, opts ...grpc.CallOption) (*String, error)
	Init(ctx context.Context, in *InitParam, opts ...grpc.CallOption) (*empty.Empty, error)
	GetClients(ctx context.Context, in *GetClientsParam, opts ...grpc.CallOption) (*ProxyClientList, error)
	GroupList(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*GroupListMessage, error)
	GroupAddInstance(ctx context.Context, in *GroupInstanceMessage, opts ...grpc.CallOption) (*empty.Empty, error)
	GroupRemoveInstance(ctx context.Context, in *GroupInstanceMessage, opts ...grpc.CallOption) (*empty.Empty, error)
	GroupGetMembers(ctx context.Context, in *String, opts ...grpc.CallOption) (*MemberListMessage, error)
	GroupDelete(ctx context.Context, in *String, opts ...grpc.CallOption) (*empty.Empty, error)
	WebsocketMessage(ctx context.Context, in *Bytes, opts ...grpc.CallOption) (*empty.Empty, error)
	KVStoreSetValue(ctx context.Context, in *KVSetValueMessage, opts ...grpc.CallOption) (*empty.Empty, error)
	KVStoreGetValue(ctx context.Context, in *KVKeyMessage, opts ...grpc.CallOption) (*String, error)
	KVStoreDeleteValue(ctx context.Context, in *KVKeyMessage, opts ...grpc.CallOption) (*empty.Empty, error)
	KVStoreList(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*KVSetValueListMessage, error)
	KVStoreClientList(ctx context.Context, in *String, opts ...grpc.CallOption) (*KVSetValueListMessage, error)
}

type proxyServiceClient struct {
	cc *grpc.ClientConn
}

func NewProxyServiceClient(cc *grpc.ClientConn) ProxyServiceClient {
	return &proxyServiceClient{cc}
}

func (c *proxyServiceClient) Ping(ctx context.Context, in *String, opts ...grpc.CallOption) (*String, error) {
	out := new(String)
	err := c.cc.Invoke(ctx, "/info_age.bremote.ProxyService/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *proxyServiceClient) Init(ctx context.Context, in *InitParam, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/info_age.bremote.ProxyService/Init", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *proxyServiceClient) GetClients(ctx context.Context, in *GetClientsParam, opts ...grpc.CallOption) (*ProxyClientList, error) {
	out := new(ProxyClientList)
	err := c.cc.Invoke(ctx, "/info_age.bremote.ProxyService/GetClients", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *proxyServiceClient) GroupList(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*GroupListMessage, error) {
	out := new(GroupListMessage)
	err := c.cc.Invoke(ctx, "/info_age.bremote.ProxyService/GroupList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *proxyServiceClient) GroupAddInstance(ctx context.Context, in *GroupInstanceMessage, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/info_age.bremote.ProxyService/GroupAddInstance", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *proxyServiceClient) GroupRemoveInstance(ctx context.Context, in *GroupInstanceMessage, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/info_age.bremote.ProxyService/GroupRemoveInstance", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *proxyServiceClient) GroupGetMembers(ctx context.Context, in *String, opts ...grpc.CallOption) (*MemberListMessage, error) {
	out := new(MemberListMessage)
	err := c.cc.Invoke(ctx, "/info_age.bremote.ProxyService/GroupGetMembers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *proxyServiceClient) GroupDelete(ctx context.Context, in *String, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/info_age.bremote.ProxyService/GroupDelete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *proxyServiceClient) WebsocketMessage(ctx context.Context, in *Bytes, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/info_age.bremote.ProxyService/WebsocketMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *proxyServiceClient) KVStoreSetValue(ctx context.Context, in *KVSetValueMessage, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/info_age.bremote.ProxyService/KVStoreSetValue", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *proxyServiceClient) KVStoreGetValue(ctx context.Context, in *KVKeyMessage, opts ...grpc.CallOption) (*String, error) {
	out := new(String)
	err := c.cc.Invoke(ctx, "/info_age.bremote.ProxyService/KVStoreGetValue", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *proxyServiceClient) KVStoreDeleteValue(ctx context.Context, in *KVKeyMessage, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/info_age.bremote.ProxyService/KVStoreDeleteValue", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *proxyServiceClient) KVStoreList(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*KVSetValueListMessage, error) {
	out := new(KVSetValueListMessage)
	err := c.cc.Invoke(ctx, "/info_age.bremote.ProxyService/KVStoreList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *proxyServiceClient) KVStoreClientList(ctx context.Context, in *String, opts ...grpc.CallOption) (*KVSetValueListMessage, error) {
	out := new(KVSetValueListMessage)
	err := c.cc.Invoke(ctx, "/info_age.bremote.ProxyService/KVStoreClientList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProxyServiceServer is the server API for ProxyService service.
type ProxyServiceServer interface {
	Ping(context.Context, *String) (*String, error)
	Init(context.Context, *InitParam) (*empty.Empty, error)
	GetClients(context.Context, *GetClientsParam) (*ProxyClientList, error)
	GroupList(context.Context, *empty.Empty) (*GroupListMessage, error)
	GroupAddInstance(context.Context, *GroupInstanceMessage) (*empty.Empty, error)
	GroupRemoveInstance(context.Context, *GroupInstanceMessage) (*empty.Empty, error)
	GroupGetMembers(context.Context, *String) (*MemberListMessage, error)
	GroupDelete(context.Context, *String) (*empty.Empty, error)
	WebsocketMessage(context.Context, *Bytes) (*empty.Empty, error)
	KVStoreSetValue(context.Context, *KVSetValueMessage) (*empty.Empty, error)
	KVStoreGetValue(context.Context, *KVKeyMessage) (*String, error)
	KVStoreDeleteValue(context.Context, *KVKeyMessage) (*empty.Empty, error)
	KVStoreList(context.Context, *empty.Empty) (*KVSetValueListMessage, error)
	KVStoreClientList(context.Context, *String) (*KVSetValueListMessage, error)
}

// UnimplementedProxyServiceServer can be embedded to have forward compatible implementations.
type UnimplementedProxyServiceServer struct {
}

func (*UnimplementedProxyServiceServer) Ping(ctx context.Context, req *String) (*String, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (*UnimplementedProxyServiceServer) Init(ctx context.Context, req *InitParam) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Init not implemented")
}
func (*UnimplementedProxyServiceServer) GetClients(ctx context.Context, req *GetClientsParam) (*ProxyClientList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetClients not implemented")
}
func (*UnimplementedProxyServiceServer) GroupList(ctx context.Context, req *empty.Empty) (*GroupListMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GroupList not implemented")
}
func (*UnimplementedProxyServiceServer) GroupAddInstance(ctx context.Context, req *GroupInstanceMessage) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GroupAddInstance not implemented")
}
func (*UnimplementedProxyServiceServer) GroupRemoveInstance(ctx context.Context, req *GroupInstanceMessage) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GroupRemoveInstance not implemented")
}
func (*UnimplementedProxyServiceServer) GroupGetMembers(ctx context.Context, req *String) (*MemberListMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GroupGetMembers not implemented")
}
func (*UnimplementedProxyServiceServer) GroupDelete(ctx context.Context, req *String) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GroupDelete not implemented")
}
func (*UnimplementedProxyServiceServer) WebsocketMessage(ctx context.Context, req *Bytes) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WebsocketMessage not implemented")
}
func (*UnimplementedProxyServiceServer) KVStoreSetValue(ctx context.Context, req *KVSetValueMessage) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method KVStoreSetValue not implemented")
}
func (*UnimplementedProxyServiceServer) KVStoreGetValue(ctx context.Context, req *KVKeyMessage) (*String, error) {
	return nil, status.Errorf(codes.Unimplemented, "method KVStoreGetValue not implemented")
}
func (*UnimplementedProxyServiceServer) KVStoreDeleteValue(ctx context.Context, req *KVKeyMessage) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method KVStoreDeleteValue not implemented")
}
func (*UnimplementedProxyServiceServer) KVStoreList(ctx context.Context, req *empty.Empty) (*KVSetValueListMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method KVStoreList not implemented")
}
func (*UnimplementedProxyServiceServer) KVStoreClientList(ctx context.Context, req *String) (*KVSetValueListMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method KVStoreClientList not implemented")
}

func RegisterProxyServiceServer(s *grpc.Server, srv ProxyServiceServer) {
	s.RegisterService(&_ProxyService_serviceDesc, srv)
}

func _ProxyService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(String)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProxyServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/info_age.bremote.ProxyService/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProxyServiceServer).Ping(ctx, req.(*String))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProxyService_Init_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitParam)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProxyServiceServer).Init(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/info_age.bremote.ProxyService/Init",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProxyServiceServer).Init(ctx, req.(*InitParam))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProxyService_GetClients_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetClientsParam)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProxyServiceServer).GetClients(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/info_age.bremote.ProxyService/GetClients",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProxyServiceServer).GetClients(ctx, req.(*GetClientsParam))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProxyService_GroupList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProxyServiceServer).GroupList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/info_age.bremote.ProxyService/GroupList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProxyServiceServer).GroupList(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProxyService_GroupAddInstance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GroupInstanceMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProxyServiceServer).GroupAddInstance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/info_age.bremote.ProxyService/GroupAddInstance",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProxyServiceServer).GroupAddInstance(ctx, req.(*GroupInstanceMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProxyService_GroupRemoveInstance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GroupInstanceMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProxyServiceServer).GroupRemoveInstance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/info_age.bremote.ProxyService/GroupRemoveInstance",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProxyServiceServer).GroupRemoveInstance(ctx, req.(*GroupInstanceMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProxyService_GroupGetMembers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(String)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProxyServiceServer).GroupGetMembers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/info_age.bremote.ProxyService/GroupGetMembers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProxyServiceServer).GroupGetMembers(ctx, req.(*String))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProxyService_GroupDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(String)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProxyServiceServer).GroupDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/info_age.bremote.ProxyService/GroupDelete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProxyServiceServer).GroupDelete(ctx, req.(*String))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProxyService_WebsocketMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Bytes)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProxyServiceServer).WebsocketMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/info_age.bremote.ProxyService/WebsocketMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProxyServiceServer).WebsocketMessage(ctx, req.(*Bytes))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProxyService_KVStoreSetValue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KVSetValueMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProxyServiceServer).KVStoreSetValue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/info_age.bremote.ProxyService/KVStoreSetValue",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProxyServiceServer).KVStoreSetValue(ctx, req.(*KVSetValueMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProxyService_KVStoreGetValue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KVKeyMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProxyServiceServer).KVStoreGetValue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/info_age.bremote.ProxyService/KVStoreGetValue",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProxyServiceServer).KVStoreGetValue(ctx, req.(*KVKeyMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProxyService_KVStoreDeleteValue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KVKeyMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProxyServiceServer).KVStoreDeleteValue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/info_age.bremote.ProxyService/KVStoreDeleteValue",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProxyServiceServer).KVStoreDeleteValue(ctx, req.(*KVKeyMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProxyService_KVStoreList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProxyServiceServer).KVStoreList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/info_age.bremote.ProxyService/KVStoreList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProxyServiceServer).KVStoreList(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProxyService_KVStoreClientList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(String)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProxyServiceServer).KVStoreClientList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/info_age.bremote.ProxyService/KVStoreClientList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProxyServiceServer).KVStoreClientList(ctx, req.(*String))
	}
	return interceptor(ctx, in, info, handler)
}

var _ProxyService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "info_age.bremote.ProxyService",
	HandlerType: (*ProxyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _ProxyService_Ping_Handler,
		},
		{
			MethodName: "Init",
			Handler:    _ProxyService_Init_Handler,
		},
		{
			MethodName: "GetClients",
			Handler:    _ProxyService_GetClients_Handler,
		},
		{
			MethodName: "GroupList",
			Handler:    _ProxyService_GroupList_Handler,
		},
		{
			MethodName: "GroupAddInstance",
			Handler:    _ProxyService_GroupAddInstance_Handler,
		},
		{
			MethodName: "GroupRemoveInstance",
			Handler:    _ProxyService_GroupRemoveInstance_Handler,
		},
		{
			MethodName: "GroupGetMembers",
			Handler:    _ProxyService_GroupGetMembers_Handler,
		},
		{
			MethodName: "GroupDelete",
			Handler:    _ProxyService_GroupDelete_Handler,
		},
		{
			MethodName: "WebsocketMessage",
			Handler:    _ProxyService_WebsocketMessage_Handler,
		},
		{
			MethodName: "KVStoreSetValue",
			Handler:    _ProxyService_KVStoreSetValue_Handler,
		},
		{
			MethodName: "KVStoreGetValue",
			Handler:    _ProxyService_KVStoreGetValue_Handler,
		},
		{
			MethodName: "KVStoreDeleteValue",
			Handler:    _ProxyService_KVStoreDeleteValue_Handler,
		},
		{
			MethodName: "KVStoreList",
			Handler:    _ProxyService_KVStoreList_Handler,
		},
		{
			MethodName: "KVStoreClientList",
			Handler:    _ProxyService_KVStoreClientList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proxy.proto",
}
