// Code generated by protoc-gen-go. DO NOT EDIT.
// source: types.proto

package api

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ProxySessionType int32

const (
	ProxySessionType_Undefined  ProxySessionType = 0
	ProxySessionType_Client     ProxySessionType = 1
	ProxySessionType_Controller ProxySessionType = 2
)

var ProxySessionType_name = map[int32]string{
	0: "Undefined",
	1: "Client",
	2: "Controller",
}

var ProxySessionType_value = map[string]int32{
	"Undefined":  0,
	"Client":     1,
	"Controller": 2,
}

func (x ProxySessionType) String() string {
	return proto.EnumName(ProxySessionType_name, int32(x))
}

func (ProxySessionType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{0}
}

type String struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *String) Reset()         { *m = String{} }
func (m *String) String() string { return proto.CompactTextString(m) }
func (*String) ProtoMessage()    {}
func (*String) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{0}
}

func (m *String) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_String.Unmarshal(m, b)
}
func (m *String) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_String.Marshal(b, m, deterministic)
}
func (m *String) XXX_Merge(src proto.Message) {
	xxx_messageInfo_String.Merge(m, src)
}
func (m *String) XXX_Size() int {
	return xxx_messageInfo_String.Size(m)
}
func (m *String) XXX_DiscardUnknown() {
	xxx_messageInfo_String.DiscardUnknown(m)
}

var xxx_messageInfo_String proto.InternalMessageInfo

func (m *String) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type Boolean struct {
	Value                bool     `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Boolean) Reset()         { *m = Boolean{} }
func (m *Boolean) String() string { return proto.CompactTextString(m) }
func (*Boolean) ProtoMessage()    {}
func (*Boolean) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{1}
}

func (m *Boolean) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Boolean.Unmarshal(m, b)
}
func (m *Boolean) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Boolean.Marshal(b, m, deterministic)
}
func (m *Boolean) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Boolean.Merge(m, src)
}
func (m *Boolean) XXX_Size() int {
	return xxx_messageInfo_Boolean.Size(m)
}
func (m *Boolean) XXX_DiscardUnknown() {
	xxx_messageInfo_Boolean.DiscardUnknown(m)
}

var xxx_messageInfo_Boolean proto.InternalMessageInfo

func (m *Boolean) GetValue() bool {
	if m != nil {
		return m.Value
	}
	return false
}

type ProxyClient struct {
	Type                 ProxySessionType `protobuf:"varint,1,opt,name=type,proto3,enum=info_age.bremote.ProxySessionType" json:"type,omitempty"`
	Instance             string           `protobuf:"bytes,2,opt,name=instance,proto3" json:"instance,omitempty"`
	Status               string           `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ProxyClient) Reset()         { *m = ProxyClient{} }
func (m *ProxyClient) String() string { return proto.CompactTextString(m) }
func (*ProxyClient) ProtoMessage()    {}
func (*ProxyClient) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{2}
}

func (m *ProxyClient) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProxyClient.Unmarshal(m, b)
}
func (m *ProxyClient) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProxyClient.Marshal(b, m, deterministic)
}
func (m *ProxyClient) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProxyClient.Merge(m, src)
}
func (m *ProxyClient) XXX_Size() int {
	return xxx_messageInfo_ProxyClient.Size(m)
}
func (m *ProxyClient) XXX_DiscardUnknown() {
	xxx_messageInfo_ProxyClient.DiscardUnknown(m)
}

var xxx_messageInfo_ProxyClient proto.InternalMessageInfo

func (m *ProxyClient) GetType() ProxySessionType {
	if m != nil {
		return m.Type
	}
	return ProxySessionType_Undefined
}

func (m *ProxyClient) GetInstance() string {
	if m != nil {
		return m.Instance
	}
	return ""
}

func (m *ProxyClient) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func init() {
	proto.RegisterEnum("info_age.bremote.ProxySessionType", ProxySessionType_name, ProxySessionType_value)
	proto.RegisterType((*String)(nil), "info_age.bremote.String")
	proto.RegisterType((*Boolean)(nil), "info_age.bremote.Boolean")
	proto.RegisterType((*ProxyClient)(nil), "info_age.bremote.ProxyClient")
}

func init() { proto.RegisterFile("types.proto", fileDescriptor_d938547f84707355) }

var fileDescriptor_d938547f84707355 = []byte{
	// 238 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0x41, 0x4b, 0x03, 0x31,
	0x10, 0x46, 0xdd, 0x56, 0xd7, 0x76, 0x8a, 0x25, 0x04, 0x91, 0x45, 0x41, 0x65, 0x4f, 0x22, 0xb8,
	0x07, 0x05, 0x6f, 0x5e, 0xda, 0x3f, 0x20, 0xad, 0x5e, 0xbc, 0x48, 0x6a, 0xa7, 0x25, 0x10, 0x67,
	0x96, 0xc9, 0xb4, 0x98, 0x7f, 0x2f, 0xa6, 0x2a, 0xba, 0xc7, 0x47, 0x1e, 0xf9, 0x1e, 0x03, 0x23,
	0x4d, 0x2d, 0xc6, 0xa6, 0x15, 0x56, 0xb6, 0xc6, 0xd3, 0x8a, 0x5f, 0xdd, 0x1a, 0x9b, 0x85, 0xe0,
	0x3b, 0x2b, 0xd6, 0xe7, 0x50, 0xce, 0x55, 0x3c, 0xad, 0xed, 0x31, 0x1c, 0x6c, 0x5d, 0xd8, 0x60,
	0x55, 0x5c, 0x16, 0x57, 0xc3, 0xd9, 0x0e, 0xea, 0x0b, 0x38, 0x9c, 0x30, 0x07, 0x74, 0xf4, 0x5f,
	0x18, 0xfc, 0x08, 0x09, 0x46, 0x8f, 0xc2, 0x1f, 0x69, 0x1a, 0x3c, 0x92, 0xda, 0x7b, 0xd8, 0xff,
	0x1a, 0xcc, 0xce, 0xf8, 0xb6, 0x6e, 0xba, 0x83, 0x4d, 0x96, 0xe7, 0x18, 0xa3, 0x67, 0x7a, 0x4a,
	0x2d, 0xce, 0xb2, 0x6f, 0x4f, 0x61, 0xe0, 0x29, 0xaa, 0xa3, 0x37, 0xac, 0x7a, 0x39, 0xe0, 0x97,
	0xed, 0x09, 0x94, 0x51, 0x9d, 0x6e, 0x62, 0xd5, 0xcf, 0x2f, 0xdf, 0x74, 0xfd, 0x00, 0xa6, 0xfb,
	0x9b, 0x3d, 0x82, 0xe1, 0x33, 0x2d, 0x71, 0xe5, 0x09, 0x97, 0x66, 0xcf, 0x02, 0x94, 0xbb, 0x30,
	0x53, 0xd8, 0x31, 0xc0, 0x94, 0x49, 0x85, 0x43, 0x40, 0x31, 0xbd, 0x49, 0x0d, 0x67, 0x84, 0x9a,
	0x0b, 0x6f, 0xfe, 0x16, 0x46, 0x94, 0x2d, 0xca, 0x4b, 0xdf, 0xb5, 0x7e, 0x51, 0xe6, 0xbb, 0xdd,
	0x7d, 0x06, 0x00, 0x00, 0xff, 0xff, 0x43, 0x37, 0x7a, 0xf4, 0x46, 0x01, 0x00, 0x00,
}
